 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/agreements", type: :request do
  # Agreement. As you add validations to Agreement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Agreement.create! valid_attributes
      get agreements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      agreement = Agreement.create! valid_attributes
      get agreement_url(agreement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_agreement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      agreement = Agreement.create! valid_attributes
      get edit_agreement_url(agreement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Agreement" do
        expect {
          post agreements_url, params: { agreement: valid_attributes }
        }.to change(Agreement, :count).by(1)
      end

      it "redirects to the created agreement" do
        post agreements_url, params: { agreement: valid_attributes }
        expect(response).to redirect_to(agreement_url(Agreement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Agreement" do
        expect {
          post agreements_url, params: { agreement: invalid_attributes }
        }.to change(Agreement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post agreements_url, params: { agreement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested agreement" do
        agreement = Agreement.create! valid_attributes
        patch agreement_url(agreement), params: { agreement: new_attributes }
        agreement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the agreement" do
        agreement = Agreement.create! valid_attributes
        patch agreement_url(agreement), params: { agreement: new_attributes }
        agreement.reload
        expect(response).to redirect_to(agreement_url(agreement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        agreement = Agreement.create! valid_attributes
        patch agreement_url(agreement), params: { agreement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agreement" do
      agreement = Agreement.create! valid_attributes
      expect {
        delete agreement_url(agreement)
      }.to change(Agreement, :count).by(-1)
    end

    it "redirects to the agreements list" do
      agreement = Agreement.create! valid_attributes
      delete agreement_url(agreement)
      expect(response).to redirect_to(agreements_url)
    end
  end
end
